#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Variables
COMMANDS_DIR="$HOME/.commands"  # استخدام $HOME لتحديد مسار الدليل
BIN_DIR="$PREFIX/bin"  # استخدام $PREFIX ليكون المسار الافتراضي للـ bin في Termux

# Check if .commands directory exists, if not, create it
if [ ! -d "$COMMANDS_DIR" ]; then
    mkdir -p "$COMMANDS_DIR"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to create .commands directory${NC}"
        exit 1
    fi
fi

# Check if argument is provided
if [ -z "$1" ]; then
    echo -e "${RED}[ERROR] Please provide a file name.${NC}"
    exit 1
fi

file=$1

# Set executable permissions
chmod +x "$file"
if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to set permissions for $file${NC}"
    exit 1
fi

# Move the file to .commands directory
mv "$file" "$COMMANDS_DIR/"
if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to move the file to $COMMANDS_DIR${NC}"
    exit 1
fi

# Create symbolic link in Termux's bin directory
ln -sf "$COMMANDS_DIR/$file" "$BIN_DIR/$file"
if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to create a symbolic link in $BIN_DIR${NC}"
    exit 1
fi

# If all steps are successful
echo -e "${GREEN}All set!${NC}"
