#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Variables
COMMANDS_DIR="/data/data/com.termux/files/home/.commands"
BIN_DIR="/data/data/com.termux/files/usr/bin"

# Check if .commands directory exists, if not, create it
if [ ! -d "$COMMANDS_DIR" ]; then
    mkdir -p "$COMMANDS_DIR"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to create .commands directory${NC}"
        exit 1
    fi
fi

# Check if argument is provided
if [ -z "$1" ]; then
    echo -e "${RED}[ERROR] Please provide a file name.${NC}"
    exit 1
fi

file=$1

# Set executable permissions
chmod +x "$file"
if [ $? -ne 0 ]; then
    echo -e "${RED}Permissions${NC}"
    exit 1
fi

# Move the file to .commands directory
mv "$file" "$COMMANDS_DIR/"
if [ $? -ne 0 ]; then
    echo -e "${RED}Transport${NC}"
    exit 1
fi

# Create symbolic link in /usr/bin
ln -sf "$COMMANDS_DIR/$file" "$BIN_DIR/$file"
if [ $? -ne 0 ]; then
    echo -e "${RED}Linking${NC}"
    exit 1
fi

# If all steps are successful
echo -e "${GREEN}All set${NC}"
