#!/bin/bash

# Get the name of the script without the path
script_name=$(basename "$0")

# Define paths
bin_path="$PREFIX/bin/$script_name"
cmnd_path="$HOME/CMND"
test_commands_path="$HOME/.commands/$script_name"

echo "Hi, this is the test subject and the cmnd command is working."

# Copy the script to the cmnd directory
cp "$bin_path" "$cmnd_path"
if [ $? -ne 0 ]; then
    echo -e "${RED}Failed to copy the script to $cmnd_path${NC}"  # إضافة لون في حالة الخطأ
    exit 1
fi

# Remove the test commands path
if [ -e "$test_commands_path" ]; then  # التحقق من وجود الملف قبل الحذف
    rm "$test_commands_path"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to remove $test_commands_path${NC}"
    fi
else
    echo "$test_commands_path does not exist, skipping removal."
fi

# Remove the binary path
if [ -e "$bin_path" ]; then  # التحقق من وجود الملف قبل الحذف
    rm "$bin_path"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to remove $bin_path${NC}"
    fi
else
    echo "$bin_path does not exist, skipping removal."
fi
